import { z } from 'zod';

export const getAppointmentParams = z.object({
  id: z.string()
})

export const AppointmentType = z.enum(['Hair', 'Skin', 'Body']);

export const registerBodySchema = z.object({
  clientId: z.string().uuid(),
  userId: z.string().uuid(),
  specialty: z.string(),
  observations: z.string().optional(),
  appointment_date: z.preprocess((arg) => {
    if (arg instanceof Date) return arg
    if (typeof arg === 'string') return new Date(arg)
  }, z.date()),
  appointment_hour: z.string(),
  presencial: z.boolean(),
  appointment_type: AppointmentType
});

export const registerBodySkinDataSchema = z.object({
  appointmentId: z.string().uuid(),
  leftFace0: z.boolean(),
  leftFace1: z.boolean(),
  leftFace2: z.boolean(),
  leftFace3: z.boolean(),
  leftFace4: z.boolean(),
  leftFace5: z.boolean(),
  leftFace6: z.boolean(),
  leftFace7: z.boolean(),
  leftFace8: z.boolean(),
  leftFace9: z.boolean(),
  leftFace10: z.boolean(),
  rightFace0: z.boolean(),
  rightFace1: z.boolean(),
  rightFace2: z.boolean(),
  rightFace3: z.boolean(),
  rightFace4: z.boolean(),
  rightFace5: z.boolean(),
  rightFace6: z.boolean(),
  rightFace7: z.boolean(),
  rightFace8: z.boolean(),
  rightFace9: z.boolean(),
  rightFace10: z.boolean(),
  frontFace0: z.boolean(),
  frontFace1: z.boolean(),
  frontFace2: z.boolean(),
  frontFace3: z.boolean(),
  frontFace4: z.boolean(),
  frontFace5: z.boolean(),
  frontFace6: z.boolean(),
  frontFace7: z.boolean(),
  frontFace8: z.boolean(),
  frontFace9: z.boolean(),
  frontFace10: z.boolean(),
  frontFace11: z.boolean(),
});

export const registerBodyBodyDataSchema = z.object({
  appointmentId: z.string().uuid(),
  backBody0: z.boolean(),
  backBody1: z.boolean(),
  backBody2: z.boolean(),
  backBody3: z.boolean(),
  backBody4: z.boolean(),
  backBody5: z.boolean(),
  backBody6: z.boolean(),
  backBody7: z.boolean(),
  backBody8: z.boolean(),
  backBody9: z.boolean(),
  backBody10: z.boolean(),
  backBody11: z.boolean(),
  backBody12: z.boolean(),
  backBody13: z.boolean(),
  backBody14: z.boolean(),
  backBody15: z.boolean(),
  backBody16: z.boolean(),
  backBody17: z.boolean(),
  backBody18: z.boolean(),
  backBody19: z.boolean(),
  backBody20: z.boolean(),
  backBody21: z.boolean(),
  frontBody0: z.boolean(),
  frontBody1: z.boolean(),
  frontBody2: z.boolean(),
  frontBody3: z.boolean(),
  frontBody4: z.boolean(),
  frontBody5: z.boolean(),
  frontBody6: z.boolean(),
  frontBody7: z.boolean(),
  frontBody8: z.boolean(),
  frontBody9: z.boolean(),
  frontBody10: z.boolean(),
  frontBody11: z.boolean(),
  frontBody12: z.boolean(),
  frontBody13: z.boolean(),
  frontBody14: z.boolean(),
  frontBody15: z.boolean(),
  frontBody16: z.boolean(),
  frontBody17: z.boolean(),
  frontBody18: z.boolean(),
  frontBody19: z.boolean(),
  frontBody20: z.boolean(),
  frontBody21: z.boolean(),
  abdomenTop: z.number().optional(),
  abdomenBottom: z.number().optional(),
  waist: z.number().optional(),
  hip: z.number().optional(),
  upperLegProxRight: z.number().optional(),
  upperLegProxLeft: z.number().optional(),
  mediumLegRight: z.number().optional(),
  mediumLegLeft: z.number().optional(),
  distalLegRight: z.number().optional(),
  distalLegLeft: z.number().optional(),
  legRight: z.number().optional(),
  legLeft: z.number().optional(),
  armRight: z.number().optional(),
  armLeft: z.number().optional(),
  chestRight: z.number().optional(),
  chestLeft: z.number().optional(),
})
