import { z } from 'zod'

export const getHealthQuestionnaireBodySchema = z.object({
  client_id: z.string(),
  problem_description: z.string().optional(),
  aesthetic_procedure: z.boolean(),
  aesthetic_procedure_description: z.string().optional(),
  cicatrization: z.boolean(),
  diabetes: z.boolean(),
  diabetes_is_controlled: z.string().optional(),
  medication_use: z.boolean(),
  medication_use_description: z.string().optional(),
  roaccutane: z.boolean(),
  medical_treatment: z.boolean(),
  medical_treatment_description: z.string().optional(),
  thrombosis: z.boolean(),
  surgery: z.boolean(),
  surgery_description: z.string().optional(),
  oncological_history: z.boolean(),
  infectious_disease: z.boolean(),
  infectious_disease_description: z.string().optional(),
  practice_sports: z.boolean(),
  practice_sports_description: z.string().optional(),
  balanced_diet: z.boolean(),
  alcohol: z.boolean(),
  drugs: z.boolean(),
  hormonal_disorder: z.boolean(),
  smoke: z.boolean(),
  sleep: z.boolean(),
  bowel_function: z.boolean(),
  hypertension: z.boolean(),
  hypertension_is_controlled: z.string().optional(),
  hypotension: z.boolean(),
  hypotension_is_controlled: z.string().optional(),
  cardiac_issues: z.boolean(),
  cardiac_issues_description: z.string().optional(),
  depression: z.boolean(),
  epilepsy: z.boolean(),
  plates_pins: z.boolean(),
  plates_pins_description: z.string().optional(),
  dental_prosthesis: z.boolean(),
  kidney_problem: z.boolean(),
  kidney_problem_description: z.string().optional(),
  liver_problem: z.boolean(),
  thyroid_problem: z.boolean(),
  auto_immune_disease: z.boolean(),
  pregnant: z.boolean(),
  breastfeeding: z.boolean(),
  sun_exposure: z.boolean(),
  sun_care: z.boolean(),
  skin_care: z.boolean(),
  methacryl_or_botulinum_toxin: z.boolean(),
  allergy_history: z.boolean(),
  herpes: z.boolean(),
  contraceptive: z.boolean(),
  menstrual_cycle: z.boolean(),
  hormones: z.boolean(),
  acid_skin: z.boolean(),
  cosmetic: z.boolean(),
  cosmetic_description: z.string().optional(),
  drink_water: z.string(),
  authorize_photos: z.boolean().optional(),
  authorize_data: z.boolean(),
})



export const getHealthQuestionnaireByClientId = z.object({
  client_id: z.string()
})
